syntax = "proto3";
package cosvian.fees.v1;

import "gogoproto/gogo.proto";
import "google/protobuf/duration.proto";
import "google/protobuf/timestamp.proto";

option go_package = "cosvian/x/fees/types";

// PriceData represents TWAP price data with metadata
message PriceData {
  option (gogoproto.equal) = true;
  string price = 1 [
    (gogoproto.customtype) = "cosmossdk.io/math.LegacyDec",
    (gogoproto.nullable) = false
  ];
  string twap_price = 2 [
    (gogoproto.customtype) = "cosmossdk.io/math.LegacyDec",
    (gogoproto.nullable) = false
  ];
  google.protobuf.Timestamp timestamp = 3 [
    (gogoproto.nullable) = false,
    (gogoproto.stdtime) = true
  ];
  google.protobuf.Duration window = 4 [
    (gogoproto.nullable) = false,
    (gogoproto.stdduration) = true
  ];
  google.protobuf.Duration freshness = 5 [
    (gogoproto.nullable) = false,
    (gogoproto.stdduration) = true
  ];
  bool is_stale = 6;
  bool is_fallback = 7;
}
