version: 1
validation: "sovereign"

default_denom: "ucsv"

accounts:
  - name: conversion_pool
    coins: ["25000000000000ucsv"] # 25M CSV

  - name: pos_infra
    coins: ["10000000000000ucsv"] # 10M CSV

  - name: exchange_fund
    coins: ["5000000000000ucsv"] # 5M CSV

  - name: norix_ecosystem
    coins: ["5000000000000ucsv"] # 5M CSV

  - name: infra_validators
    coins: ["6000000000000ucsv"] # 6M CSV

  - name: education_ops
    coins: ["4000000000000ucsv"] # 4M CSV

  - name: compliance_vault
    coins: ["5000000000000ucsv"] # 5M CSV

  - name: emergency_reserve
    coins: ["5000000000000ucsv"] # 5M CSV

  - name: strategic_growth
    coins: ["5000000000000ucsv"] # 5M CSV

  - name: team
    coins: ["8000000000000ucsv"] # 8M CSV

  - name: dao_reserve
    coins: ["4000000000000ucsv"] # 4M CSV

  - name: public_sale
    coins: ["18000000000000ucsv"] # 18M CSV

  - name: cosvian_relayer
    coins: ["0ucsv"] # 0 CSV

validators:
  - name: infra_validators
    bonded: "6000000000000ucsv"
    app:
      pruning: "nothing"
    config:
      moniker: "infra-validator"
    client:
      output: "json"

genesis:
  app_state:
    staking:
      params:
        bond_denom: "ucsv"
    mint:
      minter:
        inflation: "0.000000000000000000"
      params:
        inflation_rate_change: "0.000000000000000000"
        inflation_max: "0.000000000000000000"
        inflation_min: "0.000000000000000000"
        mint_denom: "ucsv"
    distribution:
      params:
        base_proposer_reward: "0.0"
        bonus_proposer_reward: "0.0"
        community_tax: "0.0"
    bank:
      denom_metadata:
        - base: "ucsv"
          display: "CSV"
          name: "Cosvian Token"
          symbol: "CSV"
          description: "Cosvian native token"
          denom_units:
            - denom: "ucsv"
              exponent: 0
            - denom: "CSV"
              exponent: 6
    wasm:
      params:
        code_upload_access:
          permission: "Everybody"
        instantiate_default_permission: "Everybody"
