// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: bitora/fees/v1/fee_config.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// FeeConfig defines fee amount and distribution split
type FeeConfig struct {
	UsdAmount cosmossdk_io_math.LegacyDec `protobuf:"bytes,1,opt,name=usd_amount,json=usdAmount,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"usd_amount"`
	Split     FeeSplit                    `protobuf:"bytes,2,opt,name=split,proto3" json:"split"`
}

func (m *FeeConfig) Reset()         { *m = FeeConfig{} }
func (m *FeeConfig) String() string { return proto.CompactTextString(m) }
func (*FeeConfig) ProtoMessage()    {}
func (*FeeConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_79814fcfc49bd138, []int{0}
}
func (m *FeeConfig) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *FeeConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_FeeConfig.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *FeeConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeeConfig.Merge(m, src)
}
func (m *FeeConfig) XXX_Size() int {
	return m.Size()
}
func (m *FeeConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_FeeConfig.DiscardUnknown(m)
}

var xxx_messageInfo_FeeConfig proto.InternalMessageInfo

func (m *FeeConfig) GetSplit() FeeSplit {
	if m != nil {
		return m.Split
	}
	return FeeSplit{}
}

// FeeSplit defines how fees are distributed (percentages must sum to 100)
type FeeSplit struct {
	Treasury     cosmossdk_io_math.LegacyDec `protobuf:"bytes,1,opt,name=treasury,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"treasury"`
	RetailWallet cosmossdk_io_math.LegacyDec `protobuf:"bytes,2,opt,name=retail_wallet,json=retailWallet,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"retail_wallet"`
	TokenDev     cosmossdk_io_math.LegacyDec `protobuf:"bytes,3,opt,name=token_dev,json=tokenDev,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"token_dev"`
	TokenCreator cosmossdk_io_math.LegacyDec `protobuf:"bytes,4,opt,name=token_creator,json=tokenCreator,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"token_creator"`
}

func (m *FeeSplit) Reset()         { *m = FeeSplit{} }
func (m *FeeSplit) String() string { return proto.CompactTextString(m) }
func (*FeeSplit) ProtoMessage()    {}
func (*FeeSplit) Descriptor() ([]byte, []int) {
	return fileDescriptor_79814fcfc49bd138, []int{1}
}
func (m *FeeSplit) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *FeeSplit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_FeeSplit.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *FeeSplit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeeSplit.Merge(m, src)
}
func (m *FeeSplit) XXX_Size() int {
	return m.Size()
}
func (m *FeeSplit) XXX_DiscardUnknown() {
	xxx_messageInfo_FeeSplit.DiscardUnknown(m)
}

var xxx_messageInfo_FeeSplit proto.InternalMessageInfo

func init() {
	proto.RegisterType((*FeeConfig)(nil), "bitora.fees.v1.FeeConfig")
	proto.RegisterType((*FeeSplit)(nil), "bitora.fees.v1.FeeSplit")
}

func init() { proto.RegisterFile("bitora/fees/v1/fee_config.proto", fileDescriptor_79814fcfc49bd138) }

var fileDescriptor_79814fcfc49bd138 = []byte{
	// 336 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0xbd, 0x4e, 0xc3, 0x30,
	0x14, 0x85, 0xe3, 0x52, 0x50, 0x63, 0x7e, 0x86, 0xc0, 0x10, 0x81, 0x94, 0x54, 0x65, 0xe9, 0x82,
	0xa3, 0x02, 0x13, 0x0b, 0x90, 0x56, 0x15, 0x03, 0x53, 0x19, 0x90, 0x58, 0x22, 0x37, 0xb9, 0x0d,
	0x51, 0xd3, 0xba, 0xb2, 0x9d, 0x40, 0x9f, 0x81, 0x85, 0x47, 0x60, 0xe3, 0x55, 0x3a, 0x76, 0x44,
	0x0c, 0x15, 0x6a, 0x17, 0x1e, 0x03, 0x39, 0x06, 0x24, 0x36, 0x32, 0xd9, 0xd2, 0x3d, 0xdf, 0xd1,
	0x27, 0xfb, 0x62, 0xb7, 0x9f, 0x48, 0xc6, 0xa9, 0x37, 0x00, 0x10, 0x5e, 0xde, 0x52, 0x67, 0x10,
	0xb2, 0xf1, 0x20, 0x89, 0xc9, 0x84, 0x33, 0xc9, 0xac, 0x1d, 0x1d, 0x20, 0x2a, 0x40, 0xf2, 0xd6,
	0xfe, 0x5e, 0xcc, 0x62, 0x56, 0x8c, 0x3c, 0x75, 0xd3, 0xa9, 0xc6, 0x13, 0xc2, 0x66, 0x17, 0xa0,
	0x5d, 0x90, 0x96, 0x8f, 0x71, 0x26, 0xa2, 0x80, 0x8e, 0x58, 0x36, 0x96, 0x36, 0xaa, 0xa3, 0xa6,
	0xe9, 0x1f, 0xce, 0x16, 0xae, 0xf1, 0xbe, 0x70, 0x0f, 0x42, 0x26, 0x46, 0x4c, 0x88, 0x68, 0x48,
	0x12, 0xe6, 0x8d, 0xa8, 0xbc, 0x27, 0xd7, 0x10, 0xd3, 0x70, 0xda, 0x81, 0xb0, 0x67, 0x66, 0x22,
	0xba, 0x2c, 0x28, 0xeb, 0x14, 0xaf, 0x8b, 0x49, 0x9a, 0x48, 0xbb, 0x52, 0x47, 0xcd, 0xcd, 0x63,
	0x9b, 0xfc, 0xf5, 0x20, 0x5d, 0x80, 0x1b, 0x35, 0xf7, 0xab, 0xaa, 0xb8, 0xa7, 0xc3, 0x67, 0xd5,
	0xcf, 0x17, 0x17, 0x35, 0x5e, 0x2b, 0xb8, 0xf6, 0x33, 0xb7, 0xce, 0x71, 0x4d, 0x72, 0xa0, 0x22,
	0xe3, 0xd3, 0x32, 0x2a, 0xbf, 0x90, 0x75, 0x85, 0xb7, 0x39, 0x48, 0x9a, 0xa4, 0xc1, 0x03, 0x4d,
	0x53, 0xd0, 0x46, 0xff, 0x6c, 0xd9, 0xd2, 0xe4, 0x6d, 0x01, 0x5a, 0x17, 0xd8, 0x94, 0x6c, 0x08,
	0xe3, 0x20, 0x82, 0xdc, 0x5e, 0x2b, 0xe3, 0xa2, 0xa8, 0x0e, 0xe4, 0xca, 0x45, 0x37, 0x84, 0x1c,
	0xa8, 0x64, 0xdc, 0xae, 0x96, 0x70, 0x29, 0xc8, 0xb6, 0x06, 0xf5, 0x4b, 0xf9, 0x47, 0xb3, 0xa5,
	0x83, 0xe6, 0x4b, 0x07, 0x7d, 0x2c, 0x1d, 0xf4, 0xbc, 0x72, 0x8c, 0xf9, 0xca, 0x31, 0xde, 0x56,
	0x8e, 0x71, 0xb7, 0xfb, 0xbd, 0x18, 0x8f, 0x7a, 0x35, 0xe4, 0x74, 0x02, 0xa2, 0xbf, 0x51, 0xfc,
	0xf6, 0xc9, 0x57, 0x00, 0x00, 0x00, 0xff, 0xff, 0x13, 0xb6, 0x8b, 0x1c, 0x36, 0x02, 0x00, 0x00,
}

func (this *FeeConfig) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*FeeConfig)
	if !ok {
		that2, ok := that.(FeeConfig)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.UsdAmount.Equal(that1.UsdAmount) {
		return false
	}
	if !this.Split.Equal(&that1.Split) {
		return false
	}
	return true
}
func (this *FeeSplit) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*FeeSplit)
	if !ok {
		that2, ok := that.(FeeSplit)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Treasury.Equal(that1.Treasury) {
		return false
	}
	if !this.RetailWallet.Equal(that1.RetailWallet) {
		return false
	}
	if !this.TokenDev.Equal(that1.TokenDev) {
		return false
	}
	if !this.TokenCreator.Equal(that1.TokenCreator) {
		return false
	}
	return true
}
func (m *FeeConfig) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *FeeConfig) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *FeeConfig) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Split.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintFeeConfig(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size := m.UsdAmount.Size()
		i -= size
		if _, err := m.UsdAmount.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintFeeConfig(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *FeeSplit) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *FeeSplit) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *FeeSplit) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.TokenCreator.Size()
		i -= size
		if _, err := m.TokenCreator.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintFeeConfig(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	{
		size := m.TokenDev.Size()
		i -= size
		if _, err := m.TokenDev.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintFeeConfig(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size := m.RetailWallet.Size()
		i -= size
		if _, err := m.RetailWallet.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintFeeConfig(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size := m.Treasury.Size()
		i -= size
		if _, err := m.Treasury.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintFeeConfig(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintFeeConfig(dAtA []byte, offset int, v uint64) int {
	offset -= sovFeeConfig(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *FeeConfig) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.UsdAmount.Size()
	n += 1 + l + sovFeeConfig(uint64(l))
	l = m.Split.Size()
	n += 1 + l + sovFeeConfig(uint64(l))
	return n
}

func (m *FeeSplit) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Treasury.Size()
	n += 1 + l + sovFeeConfig(uint64(l))
	l = m.RetailWallet.Size()
	n += 1 + l + sovFeeConfig(uint64(l))
	l = m.TokenDev.Size()
	n += 1 + l + sovFeeConfig(uint64(l))
	l = m.TokenCreator.Size()
	n += 1 + l + sovFeeConfig(uint64(l))
	return n
}

func sovFeeConfig(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozFeeConfig(x uint64) (n int) {
	return sovFeeConfig(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *FeeConfig) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowFeeConfig
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: FeeConfig: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: FeeConfig: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UsdAmount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFeeConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFeeConfig
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFeeConfig
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.UsdAmount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Split", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFeeConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthFeeConfig
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthFeeConfig
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Split.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipFeeConfig(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthFeeConfig
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *FeeSplit) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowFeeConfig
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: FeeSplit: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: FeeSplit: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Treasury", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFeeConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFeeConfig
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFeeConfig
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Treasury.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RetailWallet", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFeeConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFeeConfig
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFeeConfig
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.RetailWallet.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TokenDev", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFeeConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFeeConfig
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFeeConfig
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TokenDev.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TokenCreator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFeeConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFeeConfig
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFeeConfig
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TokenCreator.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipFeeConfig(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthFeeConfig
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipFeeConfig(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowFeeConfig
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowFeeConfig
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowFeeConfig
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthFeeConfig
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupFeeConfig
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthFeeConfig
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthFeeConfig        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowFeeConfig          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupFeeConfig = fmt.Errorf("proto: unexpected end of group")
)
