// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: bitora/fees/v1/params.proto

package types

import (
	fmt "fmt"
	io "io"
	math "math"
	math_bits "math/bits"

	cosmossdk_io_math "cosmossdk.io/math"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the parameters for the module.
type Params struct {
	FeeTableUsd  FeeTableUSD  `protobuf:"bytes,1,opt,name=fee_table_usd,json=feeTableUsd,proto3" json:"fee_table_usd"`
	OracleParams OracleParams `protobuf:"bytes,2,opt,name=oracle_params,json=oracleParams,proto3" json:"oracle_params"`
	GuardRails   GuardRails   `protobuf:"bytes,3,opt,name=guard_rails,json=guardRails,proto3" json:"guard_rails"`
	MinGasPolicy MinGasPolicy `protobuf:"bytes,4,opt,name=min_gas_policy,json=minGasPolicy,proto3" json:"min_gas_policy"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_e3629bd7fff90fa7, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetFeeTableUsd() FeeTableUSD {
	if m != nil {
		return m.FeeTableUsd
	}
	return FeeTableUSD{}
}

func (m *Params) GetOracleParams() OracleParams {
	if m != nil {
		return m.OracleParams
	}
	return OracleParams{}
}

func (m *Params) GetGuardRails() GuardRails {
	if m != nil {
		return m.GuardRails
	}
	return GuardRails{}
}

func (m *Params) GetMinGasPolicy() MinGasPolicy {
	if m != nil {
		return m.MinGasPolicy
	}
	return MinGasPolicy{}
}

// FeeTableUSD defines USD fee amounts and distribution splits for each category
type FeeTableUSD struct {
	PosPayment       FeeConfig `protobuf:"bytes,1,opt,name=pos_payment,json=posPayment,proto3" json:"pos_payment"`
	TokenInteraction FeeConfig `protobuf:"bytes,2,opt,name=token_interaction,json=tokenInteraction,proto3" json:"token_interaction"`
	NativeTransfer   FeeConfig `protobuf:"bytes,3,opt,name=native_transfer,json=nativeTransfer,proto3" json:"native_transfer"`
	DexNative        FeeConfig `protobuf:"bytes,4,opt,name=dex_native,json=dexNative,proto3" json:"dex_native"`
	DexUser          FeeConfig `protobuf:"bytes,5,opt,name=dex_user,json=dexUser,proto3" json:"dex_user"`
	Deploy           FeeConfig `protobuf:"bytes,6,opt,name=deploy,proto3" json:"deploy"`
	Wizard           FeeConfig `protobuf:"bytes,7,opt,name=wizard,proto3" json:"wizard"`
}

func (m *FeeTableUSD) Reset()         { *m = FeeTableUSD{} }
func (m *FeeTableUSD) String() string { return proto.CompactTextString(m) }
func (*FeeTableUSD) ProtoMessage()    {}
func (*FeeTableUSD) Descriptor() ([]byte, []int) {
	return fileDescriptor_e3629bd7fff90fa7, []int{1}
}
func (m *FeeTableUSD) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *FeeTableUSD) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_FeeTableUSD.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *FeeTableUSD) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeeTableUSD.Merge(m, src)
}
func (m *FeeTableUSD) XXX_Size() int {
	return m.Size()
}
func (m *FeeTableUSD) XXX_DiscardUnknown() {
	xxx_messageInfo_FeeTableUSD.DiscardUnknown(m)
}

var xxx_messageInfo_FeeTableUSD proto.InternalMessageInfo

func (m *FeeTableUSD) GetPosPayment() FeeConfig {
	if m != nil {
		return m.PosPayment
	}
	return FeeConfig{}
}

func (m *FeeTableUSD) GetTokenInteraction() FeeConfig {
	if m != nil {
		return m.TokenInteraction
	}
	return FeeConfig{}
}

func (m *FeeTableUSD) GetNativeTransfer() FeeConfig {
	if m != nil {
		return m.NativeTransfer
	}
	return FeeConfig{}
}

func (m *FeeTableUSD) GetDexNative() FeeConfig {
	if m != nil {
		return m.DexNative
	}
	return FeeConfig{}
}

func (m *FeeTableUSD) GetDexUser() FeeConfig {
	if m != nil {
		return m.DexUser
	}
	return FeeConfig{}
}

func (m *FeeTableUSD) GetDeploy() FeeConfig {
	if m != nil {
		return m.Deploy
	}
	return FeeConfig{}
}

func (m *FeeTableUSD) GetWizard() FeeConfig {
	if m != nil {
		return m.Wizard
	}
	return FeeConfig{}
}

// MinGasPolicy defines minimum gas price policy
type MinGasPolicy struct {
	Enabled            bool                        `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	GlobalMinGasPrice  cosmossdk_io_math.LegacyDec `protobuf:"bytes,2,opt,name=global_min_gas_price,json=globalMinGasPrice,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"global_min_gas_price"`
	AllowPerTxOverride bool                        `protobuf:"varint,3,opt,name=allow_per_tx_override,json=allowPerTxOverride,proto3" json:"allow_per_tx_override,omitempty"`
}

func (m *MinGasPolicy) Reset()         { *m = MinGasPolicy{} }
func (m *MinGasPolicy) String() string { return proto.CompactTextString(m) }
func (*MinGasPolicy) ProtoMessage()    {}
func (*MinGasPolicy) Descriptor() ([]byte, []int) {
	return fileDescriptor_e3629bd7fff90fa7, []int{2}
}
func (m *MinGasPolicy) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MinGasPolicy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MinGasPolicy.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MinGasPolicy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MinGasPolicy.Merge(m, src)
}
func (m *MinGasPolicy) XXX_Size() int {
	return m.Size()
}
func (m *MinGasPolicy) XXX_DiscardUnknown() {
	xxx_messageInfo_MinGasPolicy.DiscardUnknown(m)
}

var xxx_messageInfo_MinGasPolicy proto.InternalMessageInfo

func (m *MinGasPolicy) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

func (m *MinGasPolicy) GetAllowPerTxOverride() bool {
	if m != nil {
		return m.AllowPerTxOverride
	}
	return false
}

func init() {
	proto.RegisterType((*Params)(nil), "bitora.fees.v1.Params")
	proto.RegisterType((*FeeTableUSD)(nil), "bitora.fees.v1.FeeTableUSD")
	proto.RegisterType((*MinGasPolicy)(nil), "bitora.fees.v1.MinGasPolicy")
}

func init() { proto.RegisterFile("bitora/fees/v1/params.proto", fileDescriptor_e3629bd7fff90fa7) }

var fileDescriptor_e3629bd7fff90fa7 = []byte{
	// 609 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0x4d, 0x4f, 0x13, 0x41,
	0x18, 0xee, 0x02, 0x16, 0x98, 0x02, 0xca, 0x88, 0xc9, 0x5a, 0xb4, 0x25, 0xf5, 0x62, 0x4c, 0xdc,
	0x06, 0x3d, 0x98, 0x70, 0x30, 0x8a, 0x28, 0x98, 0xa0, 0x34, 0xb5, 0x5c, 0xbc, 0x4c, 0xa6, 0xbb,
	0x6f, 0xd7, 0x09, 0xbb, 0x3b, 0x9b, 0x99, 0xa1, 0xb4, 0xfe, 0x04, 0x4f, 0xfe, 0x04, 0x7f, 0x82,
	0x37, 0xff, 0x80, 0x07, 0x8e, 0x1c, 0x8d, 0x26, 0xc4, 0xc0, 0x41, 0x7f, 0x86, 0x99, 0x8f, 0xe2,
	0xd2, 0x90, 0xc0, 0xa5, 0x99, 0xbe, 0xef, 0xf3, 0x3c, 0xef, 0xb3, 0xcf, 0x3b, 0xbb, 0x68, 0xb9,
	0xcb, 0x14, 0x17, 0xb4, 0xd9, 0x03, 0x90, 0xcd, 0xfe, 0x6a, 0x33, 0xa7, 0x82, 0xa6, 0x32, 0xc8,
	0x05, 0x57, 0x1c, 0x2f, 0xd8, 0x66, 0xa0, 0x9b, 0x41, 0x7f, 0xb5, 0xba, 0x48, 0x53, 0x96, 0xf1,
	0xa6, 0xf9, 0xb5, 0x90, 0xea, 0x52, 0xcc, 0x63, 0x6e, 0x8e, 0x4d, 0x7d, 0x72, 0xd5, 0xfa, 0x98,
	0x6a, 0x0f, 0x80, 0x84, 0x3c, 0xeb, 0xb1, 0xd8, 0x01, 0x1a, 0x63, 0x00, 0x2e, 0x68, 0x98, 0x00,
	0x29, 0x4e, 0xaf, 0xae, 0x8c, 0x61, 0xe2, 0x7d, 0x2a, 0x22, 0x22, 0x28, 0x4b, 0x1c, 0xa2, 0xf1,
	0x7d, 0x02, 0x95, 0x5b, 0x86, 0x82, 0x5f, 0xa2, 0x79, 0x3d, 0x44, 0xd1, 0x6e, 0x02, 0x64, 0x5f,
	0x46, 0xbe, 0xb7, 0xe2, 0xdd, 0xaf, 0x3c, 0x5a, 0x0e, 0xce, 0x3f, 0x42, 0xf0, 0x0a, 0xa0, 0xa3,
	0x31, 0xbb, 0xef, 0x36, 0xd6, 0xa7, 0x0e, 0x8f, 0xeb, 0xa5, 0x76, 0xa5, 0x37, 0x2a, 0xc9, 0x08,
	0x6f, 0xa2, 0xf9, 0x73, 0x56, 0xfc, 0x09, 0x23, 0x73, 0x67, 0x5c, 0x66, 0xc7, 0x80, 0xec, 0x6c,
	0xa7, 0x33, 0xc7, 0x0b, 0x35, 0xfc, 0x1c, 0x55, 0x0a, 0x7e, 0xfd, 0x49, 0x23, 0x53, 0x1d, 0x97,
	0xd9, 0xd4, 0x90, 0xb6, 0x46, 0x38, 0x11, 0x14, 0x9f, 0x55, 0xf0, 0x16, 0x5a, 0x48, 0x59, 0x46,
	0x62, 0x2a, 0x49, 0xce, 0x13, 0x16, 0x0e, 0xfd, 0xa9, 0x8b, 0xcd, 0xbc, 0x61, 0xd9, 0x26, 0x95,
	0x2d, 0x83, 0x19, 0x99, 0x49, 0x0b, 0xb5, 0xb5, 0xbb, 0x7f, 0xbf, 0xd4, 0xbd, 0x4f, 0x7f, 0xbe,
	0x3e, 0x58, 0x72, 0x91, 0x0e, 0x6c, 0xa8, 0xd6, 0x6b, 0xe3, 0xd7, 0x24, 0xaa, 0x14, 0x72, 0xc1,
	0xcf, 0x50, 0x25, 0xe7, 0x92, 0xe4, 0x74, 0x98, 0x42, 0xa6, 0x5c, 0x92, 0xb7, 0x2f, 0x48, 0xf2,
	0x85, 0x59, 0xe9, 0xc8, 0x7a, 0xce, 0x65, 0xcb, 0x52, 0xf0, 0x36, 0x5a, 0x54, 0x7c, 0x0f, 0x32,
	0xc2, 0x32, 0x05, 0x82, 0x86, 0x8a, 0xf1, 0xcc, 0x45, 0x79, 0xa9, 0xce, 0x0d, 0xc3, 0x7c, 0xfd,
	0x9f, 0x88, 0xb7, 0xd0, 0xf5, 0x8c, 0x2a, 0xd6, 0x07, 0xa2, 0x04, 0xcd, 0x64, 0x0f, 0x84, 0xcb,
	0xf3, 0x52, 0xad, 0x05, 0xcb, 0xeb, 0x38, 0x1a, 0x7e, 0x8a, 0x50, 0x04, 0x03, 0x62, 0xab, 0x2e,
	0xce, 0x4b, 0x45, 0x66, 0x23, 0x18, 0xbc, 0x35, 0x0c, 0xbc, 0x86, 0x66, 0x34, 0x7f, 0x5f, 0x82,
	0xf0, 0xaf, 0x5d, 0x8d, 0x3d, 0x1d, 0xc1, 0x60, 0x57, 0x82, 0xc0, 0x4f, 0x50, 0x39, 0x82, 0x3c,
	0xe1, 0x43, 0xbf, 0x7c, 0x35, 0xa6, 0x83, 0x6b, 0xe2, 0x01, 0xfb, 0x48, 0x45, 0xe4, 0x4f, 0x5f,
	0x91, 0x68, 0xe1, 0x6b, 0x53, 0x7a, 0xed, 0x8d, 0x6f, 0x1e, 0x9a, 0x2b, 0xde, 0x10, 0xec, 0xa3,
	0x69, 0xc8, 0xf4, 0xae, 0xed, 0x4b, 0x32, 0xd3, 0x1e, 0xfd, 0xc5, 0x1d, 0xb4, 0x14, 0x27, 0xbc,
	0x4b, 0x13, 0x72, 0x76, 0xf1, 0x04, 0x0b, 0xc1, 0x6c, 0x6e, 0x76, 0xfd, 0x9e, 0x16, 0xff, 0x79,
	0x5c, 0x5f, 0x0e, 0xb9, 0x4c, 0xb9, 0x94, 0xd1, 0x5e, 0xc0, 0x78, 0x33, 0xa5, 0xea, 0x43, 0xb0,
	0x0d, 0x31, 0x0d, 0x87, 0x1b, 0x10, 0xb6, 0x17, 0xad, 0x80, 0x1b, 0xa8, 0xd9, 0x78, 0x15, 0xdd,
	0xa2, 0x49, 0xc2, 0x0f, 0x48, 0x0e, 0x82, 0xa8, 0x01, 0xe1, 0x7d, 0x10, 0x82, 0x45, 0x60, 0x96,
	0x38, 0xd3, 0xc6, 0xa6, 0xd9, 0x02, 0xd1, 0x19, 0xec, 0xb8, 0x8e, 0x75, 0xbe, 0xfe, 0xf0, 0xf0,
	0xa4, 0xe6, 0x1d, 0x9d, 0xd4, 0xbc, 0xdf, 0x27, 0x35, 0xef, 0xf3, 0x69, 0xad, 0x74, 0x74, 0x5a,
	0x2b, 0xfd, 0x38, 0xad, 0x95, 0xde, 0xdf, 0x3c, 0x7f, 0x8f, 0xd5, 0x30, 0x07, 0xd9, 0x2d, 0x9b,
	0x8f, 0xc2, 0xe3, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xfb, 0x7d, 0x66, 0x26, 0xd3, 0x04, 0x00,
	0x00,
}

func (this *Params) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Params)
	if !ok {
		that2, ok := that.(Params)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.FeeTableUsd.Equal(&that1.FeeTableUsd) {
		return false
	}
	if !this.OracleParams.Equal(&that1.OracleParams) {
		return false
	}
	if !this.GuardRails.Equal(&that1.GuardRails) {
		return false
	}
	if !this.MinGasPolicy.Equal(&that1.MinGasPolicy) {
		return false
	}
	return true
}
func (this *FeeTableUSD) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*FeeTableUSD)
	if !ok {
		that2, ok := that.(FeeTableUSD)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.PosPayment.Equal(&that1.PosPayment) {
		return false
	}
	if !this.TokenInteraction.Equal(&that1.TokenInteraction) {
		return false
	}
	if !this.NativeTransfer.Equal(&that1.NativeTransfer) {
		return false
	}
	if !this.DexNative.Equal(&that1.DexNative) {
		return false
	}
	if !this.DexUser.Equal(&that1.DexUser) {
		return false
	}
	if !this.Deploy.Equal(&that1.Deploy) {
		return false
	}
	if !this.Wizard.Equal(&that1.Wizard) {
		return false
	}
	return true
}
func (this *MinGasPolicy) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*MinGasPolicy)
	if !ok {
		that2, ok := that.(MinGasPolicy)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Enabled != that1.Enabled {
		return false
	}
	if !this.GlobalMinGasPrice.Equal(that1.GlobalMinGasPrice) {
		return false
	}
	if this.AllowPerTxOverride != that1.AllowPerTxOverride {
		return false
	}
	return true
}
func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.MinGasPolicy.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	{
		size, err := m.GuardRails.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size, err := m.OracleParams.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size, err := m.FeeTableUsd.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *FeeTableUSD) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *FeeTableUSD) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *FeeTableUSD) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Wizard.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x3a
	{
		size, err := m.Deploy.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x32
	{
		size, err := m.DexUser.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	{
		size, err := m.DexNative.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	{
		size, err := m.NativeTransfer.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size, err := m.TokenInteraction.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size, err := m.PosPayment.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *MinGasPolicy) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MinGasPolicy) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MinGasPolicy) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.AllowPerTxOverride {
		i--
		if m.AllowPerTxOverride {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x18
	}
	{
		size := m.GlobalMinGasPrice.Size()
		i -= size
		if _, err := m.GlobalMinGasPrice.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if m.Enabled {
		i--
		if m.Enabled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.FeeTableUsd.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.OracleParams.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.GuardRails.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.MinGasPolicy.Size()
	n += 1 + l + sovParams(uint64(l))
	return n
}

func (m *FeeTableUSD) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.PosPayment.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.TokenInteraction.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.NativeTransfer.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.DexNative.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.DexUser.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.Deploy.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.Wizard.Size()
	n += 1 + l + sovParams(uint64(l))
	return n
}

func (m *MinGasPolicy) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Enabled {
		n += 2
	}
	l = m.GlobalMinGasPrice.Size()
	n += 1 + l + sovParams(uint64(l))
	if m.AllowPerTxOverride {
		n += 2
	}
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FeeTableUsd", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.FeeTableUsd.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OracleParams", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.OracleParams.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GuardRails", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.GuardRails.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinGasPolicy", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MinGasPolicy.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *FeeTableUSD) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: FeeTableUSD: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: FeeTableUSD: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PosPayment", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.PosPayment.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TokenInteraction", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TokenInteraction.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NativeTransfer", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.NativeTransfer.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DexNative", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.DexNative.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DexUser", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.DexUser.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Deploy", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Deploy.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Wizard", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Wizard.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MinGasPolicy) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MinGasPolicy: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MinGasPolicy: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Enabled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Enabled = bool(v != 0)
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GlobalMinGasPrice", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.GlobalMinGasPrice.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AllowPerTxOverride", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.AllowPerTxOverride = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
