// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: bitora/fees/v1/oracle_params.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	github_com_cosmos_gogoproto_types "github.com/cosmos/gogoproto/types"
	_ "google.golang.org/protobuf/types/known/durationpb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// OracleParams defines Band Protocol oracle configuration
type OracleParams struct {
	BandRequestId  uint64                      `protobuf:"varint,1,opt,name=band_request_id,json=bandRequestId,proto3" json:"band_request_id,omitempty"`
	TwapWindow     time.Duration               `protobuf:"bytes,2,opt,name=twap_window,json=twapWindow,proto3,stdduration" json:"twap_window"`
	DeviationLimit cosmossdk_io_math.LegacyDec `protobuf:"bytes,3,opt,name=deviation_limit,json=deviationLimit,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"deviation_limit"`
	FallbackTtl    time.Duration               `protobuf:"bytes,4,opt,name=fallback_ttl,json=fallbackTtl,proto3,stdduration" json:"fallback_ttl"`
	MaxPriceAge    time.Duration               `protobuf:"bytes,5,opt,name=max_price_age,json=maxPriceAge,proto3,stdduration" json:"max_price_age"`
}

func (m *OracleParams) Reset()         { *m = OracleParams{} }
func (m *OracleParams) String() string { return proto.CompactTextString(m) }
func (*OracleParams) ProtoMessage()    {}
func (*OracleParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_904dffdd002ef5b0, []int{0}
}
func (m *OracleParams) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *OracleParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_OracleParams.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *OracleParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OracleParams.Merge(m, src)
}
func (m *OracleParams) XXX_Size() int {
	return m.Size()
}
func (m *OracleParams) XXX_DiscardUnknown() {
	xxx_messageInfo_OracleParams.DiscardUnknown(m)
}

var xxx_messageInfo_OracleParams proto.InternalMessageInfo

func (m *OracleParams) GetBandRequestId() uint64 {
	if m != nil {
		return m.BandRequestId
	}
	return 0
}

func (m *OracleParams) GetTwapWindow() time.Duration {
	if m != nil {
		return m.TwapWindow
	}
	return 0
}

func (m *OracleParams) GetFallbackTtl() time.Duration {
	if m != nil {
		return m.FallbackTtl
	}
	return 0
}

func (m *OracleParams) GetMaxPriceAge() time.Duration {
	if m != nil {
		return m.MaxPriceAge
	}
	return 0
}

func init() {
	proto.RegisterType((*OracleParams)(nil), "bitora.fees.v1.OracleParams")
}

func init() {
	proto.RegisterFile("bitora/fees/v1/oracle_params.proto", fileDescriptor_904dffdd002ef5b0)
}

var fileDescriptor_904dffdd002ef5b0 = []byte{
	// 359 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x91, 0xcd, 0x4a, 0xeb, 0x40,
	0x14, 0xc7, 0x33, 0xbd, 0xbd, 0x97, 0x7b, 0xa7, 0x5f, 0x90, 0xeb, 0x22, 0x56, 0x48, 0x4b, 0x05,
	0xe9, 0xc6, 0x09, 0xd5, 0x27, 0xb0, 0x14, 0x45, 0x28, 0x58, 0x82, 0x20, 0xb8, 0x19, 0x4e, 0x92,
	0x69, 0x1c, 0x9a, 0x74, 0x62, 0x32, 0xfd, 0x7a, 0x0b, 0x97, 0x3e, 0x52, 0x97, 0x5d, 0x8a, 0x42,
	0x95, 0xf6, 0x45, 0x64, 0x26, 0xad, 0x6b, 0xdd, 0x25, 0xe7, 0xfc, 0x7e, 0xff, 0xff, 0xc0, 0xc1,
	0x2d, 0x8f, 0x4b, 0x91, 0x82, 0x33, 0x64, 0x2c, 0x73, 0xa6, 0x1d, 0x47, 0xa4, 0xe0, 0x47, 0x8c,
	0x26, 0x90, 0x42, 0x9c, 0x91, 0x24, 0x15, 0x52, 0x98, 0xd5, 0x9c, 0x21, 0x8a, 0x21, 0xd3, 0x4e,
	0xfd, 0x20, 0x14, 0xa1, 0xd0, 0x2b, 0x47, 0x7d, 0xe5, 0x54, 0xdd, 0x0e, 0x85, 0x08, 0x23, 0xe6,
	0xe8, 0x3f, 0x6f, 0x32, 0x74, 0x82, 0x49, 0x0a, 0x92, 0x8b, 0x71, 0xbe, 0x6f, 0xbd, 0x15, 0x70,
	0xf9, 0x46, 0xa7, 0x0f, 0x74, 0xb8, 0x79, 0x82, 0x6b, 0x1e, 0x8c, 0x03, 0x9a, 0xb2, 0xc7, 0x09,
	0xcb, 0x24, 0xe5, 0x81, 0x85, 0x9a, 0xa8, 0x5d, 0x74, 0x2b, 0x6a, 0xec, 0xe6, 0xd3, 0xeb, 0xc0,
	0xec, 0xe1, 0x92, 0x9c, 0x41, 0x42, 0x67, 0x7c, 0x1c, 0x88, 0x99, 0x55, 0x68, 0xa2, 0x76, 0xe9,
	0xec, 0x90, 0xe4, 0x75, 0x64, 0x5f, 0x47, 0x7a, 0xbb, 0xba, 0xee, 0xdf, 0xe5, 0xba, 0x61, 0x3c,
	0xbf, 0x37, 0x90, 0x8b, 0x95, 0x77, 0xa7, 0x35, 0xb3, 0x8f, 0x6b, 0x01, 0x9b, 0x72, 0x8d, 0xd0,
	0x88, 0xc7, 0x5c, 0x5a, 0xbf, 0x9a, 0xa8, 0xfd, 0xaf, 0x7b, 0xac, 0xf0, 0xd7, 0x75, 0xe3, 0xc8,
	0x17, 0x59, 0x2c, 0xb2, 0x2c, 0x18, 0x11, 0x2e, 0x9c, 0x18, 0xe4, 0x03, 0xe9, 0xb3, 0x10, 0xfc,
	0x45, 0x8f, 0xf9, 0x6e, 0xf5, 0xcb, 0xed, 0x2b, 0xd5, 0xbc, 0xc4, 0xe5, 0x21, 0x44, 0x91, 0x07,
	0xfe, 0x88, 0x4a, 0x19, 0x59, 0xc5, 0xef, 0x3f, 0xaa, 0xb4, 0x17, 0x6f, 0x65, 0x64, 0x5e, 0xe1,
	0x4a, 0x0c, 0x73, 0x9a, 0xa4, 0xdc, 0x67, 0x14, 0x42, 0x66, 0xfd, 0xfe, 0x41, 0x50, 0x0c, 0xf3,
	0x81, 0x12, 0x2f, 0x42, 0xd6, 0x3d, 0x5d, 0x6e, 0x6c, 0xb4, 0xda, 0xd8, 0xe8, 0x63, 0x63, 0xa3,
	0xa7, 0xad, 0x6d, 0xac, 0xb6, 0xb6, 0xf1, 0xb2, 0xb5, 0x8d, 0xfb, 0xff, 0xbb, 0x0b, 0xcf, 0xf3,
	0x1b, 0xcb, 0x45, 0xc2, 0x32, 0xef, 0x8f, 0x0e, 0x3e, 0xff, 0x0c, 0x00, 0x00, 0xff, 0xff, 0xd4,
	0x0f, 0x6d, 0x70, 0xff, 0x01, 0x00, 0x00,
}

func (m *OracleParams) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *OracleParams) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *OracleParams) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	n1, err1 := github_com_cosmos_gogoproto_types.StdDurationMarshalTo(m.MaxPriceAge, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.MaxPriceAge):])
	if err1 != nil {
		return 0, err1
	}
	i -= n1
	i = encodeVarintOracleParams(dAtA, i, uint64(n1))
	i--
	dAtA[i] = 0x2a
	n2, err2 := github_com_cosmos_gogoproto_types.StdDurationMarshalTo(m.FallbackTtl, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.FallbackTtl):])
	if err2 != nil {
		return 0, err2
	}
	i -= n2
	i = encodeVarintOracleParams(dAtA, i, uint64(n2))
	i--
	dAtA[i] = 0x22
	{
		size := m.DeviationLimit.Size()
		i -= size
		if _, err := m.DeviationLimit.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintOracleParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	n3, err3 := github_com_cosmos_gogoproto_types.StdDurationMarshalTo(m.TwapWindow, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.TwapWindow):])
	if err3 != nil {
		return 0, err3
	}
	i -= n3
	i = encodeVarintOracleParams(dAtA, i, uint64(n3))
	i--
	dAtA[i] = 0x12
	if m.BandRequestId != 0 {
		i = encodeVarintOracleParams(dAtA, i, uint64(m.BandRequestId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintOracleParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovOracleParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *OracleParams) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.BandRequestId != 0 {
		n += 1 + sovOracleParams(uint64(m.BandRequestId))
	}
	l = github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.TwapWindow)
	n += 1 + l + sovOracleParams(uint64(l))
	l = m.DeviationLimit.Size()
	n += 1 + l + sovOracleParams(uint64(l))
	l = github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.FallbackTtl)
	n += 1 + l + sovOracleParams(uint64(l))
	l = github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.MaxPriceAge)
	n += 1 + l + sovOracleParams(uint64(l))
	return n
}

func sovOracleParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozOracleParams(x uint64) (n int) {
	return sovOracleParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *OracleParams) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowOracleParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: OracleParams: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: OracleParams: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BandRequestId", wireType)
			}
			m.BandRequestId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOracleParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BandRequestId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TwapWindow", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOracleParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthOracleParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthOracleParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdDurationUnmarshal(&m.TwapWindow, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DeviationLimit", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOracleParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthOracleParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthOracleParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.DeviationLimit.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FallbackTtl", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOracleParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthOracleParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthOracleParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdDurationUnmarshal(&m.FallbackTtl, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxPriceAge", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOracleParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthOracleParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthOracleParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdDurationUnmarshal(&m.MaxPriceAge, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipOracleParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthOracleParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipOracleParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowOracleParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowOracleParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowOracleParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthOracleParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupOracleParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthOracleParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthOracleParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowOracleParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupOracleParams = fmt.Errorf("proto: unexpected end of group")
)
