// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cosvian/fees/v1/price_data.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	github_com_cosmos_gogoproto_types "github.com/cosmos/gogoproto/types"
	_ "google.golang.org/protobuf/types/known/durationpb"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// PriceData represents TWAP price data with metadata
type PriceData struct {
	Price      cosmossdk_io_math.LegacyDec `protobuf:"bytes,1,opt,name=price,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"price"`
	TwapPrice  cosmossdk_io_math.LegacyDec `protobuf:"bytes,2,opt,name=twap_price,json=twapPrice,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"twap_price"`
	Timestamp  time.Time                   `protobuf:"bytes,3,opt,name=timestamp,proto3,stdtime" json:"timestamp"`
	Window     time.Duration               `protobuf:"bytes,4,opt,name=window,proto3,stdduration" json:"window"`
	Freshness  time.Duration               `protobuf:"bytes,5,opt,name=freshness,proto3,stdduration" json:"freshness"`
	IsStale    bool                        `protobuf:"varint,6,opt,name=is_stale,json=isStale,proto3" json:"is_stale,omitempty"`
	IsFallback bool                        `protobuf:"varint,7,opt,name=is_fallback,json=isFallback,proto3" json:"is_fallback,omitempty"`
}

func (m *PriceData) Reset()         { *m = PriceData{} }
func (m *PriceData) String() string { return proto.CompactTextString(m) }
func (*PriceData) ProtoMessage()    {}
func (*PriceData) Descriptor() ([]byte, []int) {
	return fileDescriptor_424fe1976bbfb12c, []int{0}
}
func (m *PriceData) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PriceData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PriceData.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PriceData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PriceData.Merge(m, src)
}
func (m *PriceData) XXX_Size() int {
	return m.Size()
}
func (m *PriceData) XXX_DiscardUnknown() {
	xxx_messageInfo_PriceData.DiscardUnknown(m)
}

var xxx_messageInfo_PriceData proto.InternalMessageInfo

func (m *PriceData) GetTimestamp() time.Time {
	if m != nil {
		return m.Timestamp
	}
	return time.Time{}
}

func (m *PriceData) GetWindow() time.Duration {
	if m != nil {
		return m.Window
	}
	return 0
}

func (m *PriceData) GetFreshness() time.Duration {
	if m != nil {
		return m.Freshness
	}
	return 0
}

func (m *PriceData) GetIsStale() bool {
	if m != nil {
		return m.IsStale
	}
	return false
}

func (m *PriceData) GetIsFallback() bool {
	if m != nil {
		return m.IsFallback
	}
	return false
}

func init() {
	proto.RegisterType((*PriceData)(nil), "cosvian.fees.v1.PriceData")
}

func init() { proto.RegisterFile("cosvian/fees/v1/price_data.proto", fileDescriptor_424fe1976bbfb12c) }

var fileDescriptor_424fe1976bbfb12c = []byte{
	// 376 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xbd, 0x6e, 0xe2, 0x40,
	0x14, 0x85, 0x3d, 0xcb, 0xaf, 0x87, 0x62, 0x25, 0x8b, 0xc2, 0xb0, 0x92, 0x6d, 0xed, 0x36, 0x54,
	0x63, 0xb1, 0x5b, 0xed, 0x6e, 0xb5, 0x16, 0xda, 0x2a, 0x05, 0x22, 0xa9, 0xd2, 0x58, 0x83, 0x3d,
	0x36, 0x23, 0x6c, 0x8f, 0xe5, 0x3b, 0x40, 0x78, 0x0b, 0xca, 0x94, 0x79, 0x1c, 0x4a, 0xca, 0x28,
	0x05, 0x89, 0xa0, 0xc9, 0x63, 0x44, 0xfe, 0x21, 0x48, 0x49, 0x43, 0x37, 0x77, 0xce, 0xf9, 0xce,
	0xdc, 0x3b, 0xba, 0xd8, 0xf2, 0x04, 0x2c, 0x39, 0x4d, 0xec, 0x80, 0x31, 0xb0, 0x97, 0x43, 0x3b,
	0xcd, 0xb8, 0xc7, 0x5c, 0x9f, 0x4a, 0x4a, 0xd2, 0x4c, 0x48, 0xa1, 0x7d, 0xad, 0x1c, 0x24, 0x77,
	0x90, 0xe5, 0xb0, 0xdf, 0x0d, 0x45, 0x28, 0x0a, 0xcd, 0xce, 0x4f, 0xa5, 0xad, 0x6f, 0x84, 0x42,
	0x84, 0x11, 0xb3, 0x8b, 0x6a, 0xba, 0x08, 0x6c, 0x7f, 0x91, 0x51, 0xc9, 0x45, 0x52, 0xe9, 0xe6,
	0x47, 0x5d, 0xf2, 0x98, 0x81, 0xa4, 0x71, 0x5a, 0x1a, 0xbe, 0x6f, 0x6a, 0x58, 0x1d, 0xe7, 0x8f,
	0x8f, 0xa8, 0xa4, 0xda, 0x6f, 0xdc, 0x28, 0x3a, 0xd1, 0x91, 0x85, 0x06, 0xaa, 0xf3, 0x63, 0xbb,
	0x37, 0x95, 0xa7, 0xbd, 0xf9, 0xcd, 0x13, 0x10, 0x0b, 0x00, 0x7f, 0x4e, 0xb8, 0xb0, 0x63, 0x2a,
	0x67, 0xe4, 0x8a, 0x85, 0xd4, 0x5b, 0x8f, 0x98, 0x37, 0x29, 0x09, 0xcd, 0xc1, 0x58, 0xae, 0x68,
	0xea, 0x96, 0xfc, 0x97, 0xcb, 0x79, 0x35, 0xc7, 0xc6, 0x55, 0x86, 0xfa, 0xde, 0x9f, 0x5e, 0xb3,
	0xd0, 0xa0, 0xf3, 0xb3, 0x4f, 0xca, 0x09, 0xc8, 0x69, 0x02, 0x72, 0x73, 0x72, 0x38, 0xed, 0x3c,
	0x7e, 0xf3, 0x6c, 0xa2, 0xc9, 0x19, 0xd3, 0xfe, 0xe2, 0xe6, 0x8a, 0x27, 0xbe, 0x58, 0xe9, 0xf5,
	0x22, 0xa0, 0xf7, 0x29, 0x60, 0x54, 0x7d, 0x51, 0xc9, 0xdf, 0xe7, 0x7c, 0x85, 0x68, 0xff, 0xb0,
	0x1a, 0x64, 0x0c, 0x66, 0x09, 0x03, 0xd0, 0x1b, 0x97, 0xf3, 0x67, 0x4a, 0xeb, 0xe1, 0x36, 0x07,
	0x17, 0x24, 0x8d, 0x98, 0xde, 0xb4, 0xd0, 0xa0, 0x3d, 0x69, 0x71, 0xb8, 0xce, 0x4b, 0xcd, 0xc4,
	0x1d, 0x0e, 0x6e, 0x40, 0xa3, 0x68, 0x4a, 0xbd, 0xb9, 0xde, 0x2a, 0x54, 0xcc, 0xe1, 0x7f, 0x75,
	0xf3, 0xa7, 0xfe, 0xfa, 0x60, 0x22, 0x87, 0x6c, 0x0f, 0x06, 0xda, 0x1d, 0x0c, 0xf4, 0x72, 0x30,
	0xd0, 0xe6, 0x68, 0x28, 0xbb, 0xa3, 0xa1, 0x3c, 0x1e, 0x0d, 0xe5, 0xb6, 0x7b, 0x5a, 0x9b, 0xbb,
	0x72, 0x71, 0xe4, 0x3a, 0x65, 0x30, 0x6d, 0x16, 0x9d, 0xfd, 0x7a, 0x0b, 0x00, 0x00, 0xff, 0xff,
	0xc6, 0xf1, 0xa1, 0x18, 0x55, 0x02, 0x00, 0x00,
}

func (this *PriceData) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*PriceData)
	if !ok {
		that2, ok := that.(PriceData)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Price.Equal(that1.Price) {
		return false
	}
	if !this.TwapPrice.Equal(that1.TwapPrice) {
		return false
	}
	if !this.Timestamp.Equal(that1.Timestamp) {
		return false
	}
	if this.Window != that1.Window {
		return false
	}
	if this.Freshness != that1.Freshness {
		return false
	}
	if this.IsStale != that1.IsStale {
		return false
	}
	if this.IsFallback != that1.IsFallback {
		return false
	}
	return true
}
func (m *PriceData) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PriceData) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PriceData) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.IsFallback {
		i--
		if m.IsFallback {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x38
	}
	if m.IsStale {
		i--
		if m.IsStale {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x30
	}
	n1, err1 := github_com_cosmos_gogoproto_types.StdDurationMarshalTo(m.Freshness, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.Freshness):])
	if err1 != nil {
		return 0, err1
	}
	i -= n1
	i = encodeVarintPriceData(dAtA, i, uint64(n1))
	i--
	dAtA[i] = 0x2a
	n2, err2 := github_com_cosmos_gogoproto_types.StdDurationMarshalTo(m.Window, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.Window):])
	if err2 != nil {
		return 0, err2
	}
	i -= n2
	i = encodeVarintPriceData(dAtA, i, uint64(n2))
	i--
	dAtA[i] = 0x22
	n3, err3 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(m.Timestamp, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(m.Timestamp):])
	if err3 != nil {
		return 0, err3
	}
	i -= n3
	i = encodeVarintPriceData(dAtA, i, uint64(n3))
	i--
	dAtA[i] = 0x1a
	{
		size := m.TwapPrice.Size()
		i -= size
		if _, err := m.TwapPrice.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintPriceData(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size := m.Price.Size()
		i -= size
		if _, err := m.Price.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintPriceData(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintPriceData(dAtA []byte, offset int, v uint64) int {
	offset -= sovPriceData(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *PriceData) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Price.Size()
	n += 1 + l + sovPriceData(uint64(l))
	l = m.TwapPrice.Size()
	n += 1 + l + sovPriceData(uint64(l))
	l = github_com_cosmos_gogoproto_types.SizeOfStdTime(m.Timestamp)
	n += 1 + l + sovPriceData(uint64(l))
	l = github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.Window)
	n += 1 + l + sovPriceData(uint64(l))
	l = github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.Freshness)
	n += 1 + l + sovPriceData(uint64(l))
	if m.IsStale {
		n += 2
	}
	if m.IsFallback {
		n += 2
	}
	return n
}

func sovPriceData(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozPriceData(x uint64) (n int) {
	return sovPriceData(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *PriceData) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPriceData
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PriceData: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PriceData: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Price", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPriceData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPriceData
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPriceData
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Price.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TwapPrice", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPriceData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPriceData
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPriceData
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TwapPrice.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Timestamp", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPriceData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPriceData
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPriceData
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(&m.Timestamp, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Window", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPriceData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPriceData
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPriceData
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdDurationUnmarshal(&m.Window, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Freshness", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPriceData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPriceData
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPriceData
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdDurationUnmarshal(&m.Freshness, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsStale", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPriceData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.IsStale = bool(v != 0)
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsFallback", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPriceData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.IsFallback = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipPriceData(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPriceData
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipPriceData(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowPriceData
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPriceData
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPriceData
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthPriceData
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupPriceData
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthPriceData
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthPriceData        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowPriceData          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupPriceData = fmt.Errorf("proto: unexpected end of group")
)
