#!/usr/bin/env bash
# Generate & (optionally) submit an osmosisicq MsgUpdateParams governance proposal.
# Usage:
#   ./scripts/osmosisicq_make_proposal.sh [--submit] [--vote] [--deposit <amt>] \
#        --connection connection-0 --pool 666 --base uosmo \
#        --quote ibc/<HASH> [--no-twap] [--interval 30] [--min-liq 0] [--max-dev 0.8]
#
# Requirements:
#   - bitorad binary running (same version / build tag icq_async)
#   - FUND_SOURCE account exists in keyring-backend test
#   - Environment vars: BITORA_CHAIN, FUND_SOURCE, RELAYER_FEE (optional)
#
set -euo pipefail

INTERVAL=30
POOL_ID=0
BASE=""
QUOTE=""
USE_TWAP=1
TWAP_WINDOW=300
MIN_LIQ=0
MAX_DEV=0.8
DEPOSIT_AMT=1000000ubto
SUBMIT=0
VOTE=0
PROPOSAL_FILE=/tmp/osmo_params.json

while [[ $# -gt 0 ]]; do
  case $1 in
    --connection) CONNECTION_ID=$2; shift 2 ;;
    --pool) POOL_ID=$2; shift 2 ;;
    --base) BASE=$2; shift 2 ;;
    --quote) QUOTE=$2; shift 2 ;;
    --interval) INTERVAL=$2; shift 2 ;;
    --min-liq) MIN_LIQ=$2; shift 2 ;;
    --max-dev) MAX_DEV=$2; shift 2 ;;
    --twap-window) TWAP_WINDOW=$2; shift 2 ;;
    --no-twap) USE_TWAP=0; shift ;;
    --deposit) DEPOSIT_AMT=$2; shift 2 ;;
    --submit) SUBMIT=1; shift ;;
    --vote) VOTE=1; shift ;;
    --file) PROPOSAL_FILE=$2; shift 2 ;;
    *) echo "Unknown arg: $1" >&2; exit 1 ;;
  esac
done

: "${BITORA_CHAIN:?env BITORA_CHAIN required}"
: "${FUND_SOURCE:?env FUND_SOURCE required}"
RELAYER_FEE=${RELAYER_FEE:-500000ubto}
BROADCAST_MODE=${BROADCAST_MODE:-sync}
TX_POLL_MAX=${TX_POLL_MAX:-40}
TX_POLL_INTERVAL=${TX_POLL_INTERVAL:-2}

if [[ "$BROADCAST_MODE" == "block" ]]; then
  echo "[WARN] BROADCAST_MODE=block unsupported by bitorad; defaulting to sync" >&2
  BROADCAST_MODE=sync
elif [[ "$BROADCAST_MODE" != "sync" && "$BROADCAST_MODE" != "async" ]]; then
  echo "[WARN] BROADCAST_MODE=$BROADCAST_MODE invalid; defaulting to sync" >&2
  BROADCAST_MODE=sync
fi

if [[ -z "${CONNECTION_ID:-}" ]]; then echo "--connection required" >&2; exit 1; fi
if [[ -z "$BASE" || -z "$QUOTE" ]]; then echo "--base and --quote required" >&2; exit 1; fi
if [[ $USE_TWAP -eq 1 && $TWAP_WINDOW -eq 0 ]]; then echo "TWAP window must be > 0 when TWAP enabled" >&2; exit 1; fi

# determine pagination flags supported by this bitorad binary
QUERY_PAGINATION_ARGS=()
if GOV_HELP=$(bitorad q gov proposals --help 2>/dev/null); then
  if grep -q -- '--pagination.limit' <<<"$GOV_HELP"; then
    QUERY_PAGINATION_ARGS=(--pagination.limit 200)
  elif grep -q -- '--limit' <<<"$GOV_HELP"; then
    QUERY_PAGINATION_ARGS=(--limit 200)
  fi
fi

# Resolve gov module authority address
GOV=$(bitorad q auth module-accounts -o json 2>/dev/null | jq -r '.accounts[] | select(.value.name=="gov") | .value.address')
if [[ -z "$GOV" || "$GOV" == null ]]; then
  GOV=$(jq -r '.app_state.auth.accounts[] | select(.name=="gov") | .base_account.address // empty' "$HOME/.bitora/config/genesis.json" 2>/dev/null || true)
fi
if [[ -z "$GOV" ]]; then echo "Failed to resolve gov authority" >&2; exit 1; fi

cat > "$PROPOSAL_FILE" <<JSON
{
  "messages": [
    {
      "@type": "/bitora.osmosisicq.v1.MsgUpdateParams",
      "authority": "$GOV",
      "params": {
        "connection_id": "$CONNECTION_ID",
        "update_interval_seconds": $INTERVAL,
        "pool_id": $POOL_ID,
        "base_denom": "$BASE",
        "quote_denom": "$QUOTE",
        "use_twap": $( [[ $USE_TWAP -eq 1 ]] && echo true || echo false ),
        "twap_window_seconds": $TWAP_WINDOW,
        "min_liquidity": "$MIN_LIQ",
        "max_deviation": "$MAX_DEV"
      }
    }
  ],
  "deposit": "$DEPOSIT_AMT",
  "title": "Update osmosisicq params",
  "summary": "Auto-generated by helper script"
}
JSON

echo "[INFO] Wrote proposal JSON to $PROPOSAL_FILE" >&2
jq '.' "$PROPOSAL_FILE" >/dev/null || { echo "Invalid JSON" >&2; exit 1; }

echo "[INFO] Sanity checking type wrapper..." >&2
WRAP_TYPE=$(bitorad tx gov submit-proposal "$PROPOSAL_FILE" --from $FUND_SOURCE --chain-id $BITORA_CHAIN --fees $RELAYER_FEE --keyring-backend test --generate-only -o json | jq -r '.body.messages[0]."@type"')
INNER_TYPE=$(bitorad tx gov submit-proposal "$PROPOSAL_FILE" --from $FUND_SOURCE --chain-id $BITORA_CHAIN --fees $RELAYER_FEE --keyring-backend test --generate-only -o json | jq -r '.body.messages[0].messages[0]."@type"')

echo "Wrapper: $WRAP_TYPE" >&2
echo "Inner:   $INNER_TYPE" >&2
if [[ "$WRAP_TYPE" != "/cosmos.gov.v1.MsgSubmitProposal" ]]; then echo "[WARN] Unexpected wrapper type: $WRAP_TYPE" >&2; fi
if [[ "$INNER_TYPE" != "/bitora.osmosisicq.v1.MsgUpdateParams" ]]; then echo "[ERROR] Unexpected inner type: $INNER_TYPE" >&2; fi

if [[ $SUBMIT -eq 1 ]]; then
  echo "[INFO] Broadcasting proposal..." >&2
  PRE_LAST=$(bitorad q gov proposals "${QUERY_PAGINATION_ARGS[@]}" -o json 2>/dev/null | jq -r '.proposals | last? | .proposal_id // 0')
  TX=$(bitorad tx gov submit-proposal "$PROPOSAL_FILE" \
    --from $FUND_SOURCE --chain-id $BITORA_CHAIN \
    --fees $RELAYER_FEE --keyring-backend test \
    --broadcast-mode "$BROADCAST_MODE" -y -o json)
  echo "$TX" > /tmp/submit_osmosisicq_proposal.json
  CODE=$(echo "$TX" | jq -r '.code // 0')
  if [[ "$CODE" != "0" ]]; then
    echo "[ERROR] Submit proposal failed code=$CODE" >&2
    echo "$TX" | jq '{code,raw_log}' >&2
    exit 1
  fi

  TXHASH=$(echo "$TX" | jq -r '.txhash // empty')
  PARSE_TARGET="$TX"
  TX_CONFIRMED=0
  if [[ -n "$TXHASH" ]]; then
    ATTEMPT=0
    while (( ATTEMPT < TX_POLL_MAX )); do
      DELIVER_JSON=$(bitorad q tx "$TXHASH" -o json 2>/dev/null || true)
      if [[ -n "$DELIVER_JSON" ]] && jq -e '.raw_log != null and .raw_log != ""' <<<"$DELIVER_JSON" >/dev/null 2>&1; then
        DELIVER_CODE=$(jq -r '.code // 0' <<<"$DELIVER_JSON")
        if [[ "$DELIVER_CODE" != "0" ]]; then
          echo "[ERROR] DeliverTx failed code=$DELIVER_CODE" >&2
          jq '{code,raw_log}' <<<"$DELIVER_JSON" >&2
          exit 1
        fi
        echo "$DELIVER_JSON" > /tmp/submit_osmosisicq_proposal_deliver.json
        PARSE_TARGET="$DELIVER_JSON"
        TX_CONFIRMED=1
        break
      fi
      ((ATTEMPT++))
      sleep "$TX_POLL_INTERVAL"
    done
  fi
  if [[ $TX_CONFIRMED -eq 0 && -n "$TXHASH" ]]; then
    echo "[WARN] Proposal tx not yet found in a block (hash=$TXHASH); inferring via proposal list" >&2
  fi

  PROPID=$(jq -r '[.logs[]? | .events[]?
    | select(.type=="submit_proposal")
    | .attributes[]?
    | select(.key=="proposal_id")
    | .value] | first // empty' <<<"$PARSE_TARGET")
  if [[ -z "$PROPID" || "$PROPID" == null ]]; then
    PROPID=$(jq -r '[.events[]?
      | select(.type=="submit_proposal")
      | .attributes[]?
      | select(.key=="proposal_id")
      | .value] | first // empty' <<<"$PARSE_TARGET")
  fi
  if [[ -z "$PROPID" || "$PROPID" == null ]]; then
    ATTEMPT=0
    while (( ATTEMPT < 10 )); do
      sleep 1
      POST_LAST=$(bitorad q gov proposals "${QUERY_PAGINATION_ARGS[@]}" -o json 2>/dev/null | jq -r '.proposals | last? | .proposal_id // 0')
      if [[ -n "$POST_LAST" && "$POST_LAST" != "0" && "$POST_LAST" != "$PRE_LAST" ]]; then
        PROPID=$POST_LAST
        echo "[INFO] Fallback proposal id: $PROPID" >&2
        break
      fi
      ((ATTEMPT++))
    done
  fi
  if [[ -z "$PROPID" || "$PROPID" == null ]]; then
    echo "[ERROR] Unable to determine proposal id (no events and no new proposal detected)" >&2
    exit 1
  fi
  echo "[INFO] Proposal ID: $PROPID" >&2
  if [[ -n "$PROPID" && $PROPID != null ]]; then
    echo "[INFO] Depositing $DEPOSIT_AMT..." >&2
    bitorad tx gov deposit $PROPID $DEPOSIT_AMT --from $FUND_SOURCE --chain-id $BITORA_CHAIN --fees $RELAYER_FEE --keyring-backend test --broadcast-mode "$BROADCAST_MODE" -y >/dev/null
    if [[ $VOTE -eq 1 ]]; then
      echo "[INFO] Voting YES..." >&2
      bitorad tx gov vote $PROPID yes --from $FUND_SOURCE --chain-id $BITORA_CHAIN --fees $RELAYER_FEE --keyring-backend test --broadcast-mode "$BROADCAST_MODE" -y >/dev/null
    fi
    echo "[INFO] Track status: bitorad q gov proposal $PROPID -o json | jq -r '.status'" >&2
  fi
fi
